### ISSUE TITLE
Awesome repository, any chance the paper can be open too? :)

### ISSUE THREAD

**Issue by blazespinnaker** [ShahidIqb/PROST#1]
I couldn't find a freely available PDF for the associated paper, "PROST: AlphaFold2-aware Sequence-Based Predictor to Estimate Protein Stability Changes upon Missense Mutations".  Is it possible to make it freely available?

**Comment by ShahidIqb** [comment]
Can you please send me a request for the paper on ResearchGate https://www.researchgate.net/publication/362513277_PROST_AlphaFold2-aware_sequence-based_predictor_to_estimate_protein_stability_changes_upon_missense_mutations
