### ISSUE TITLE
matrices dont match

### ISSUE THREAD

**Issue by Ravy-LFL** [ShahidIqb/PROST#2]
Hi,

I got this error when running `spider3_pred.py` : 
"""
Traceback (most recent call last):
  File "/PATH/MTDSITE/MTDsite/code/PROST/script/spider3_pred.py", line 280, in <module>
    run_all(list_dict_nn, [bn], opts)
  File "/PATH/MTDSITE/MTDsite/code/PROST/script/spider3_pred.py", line 127, in run_all
    out1 = run_batch1(check_dat[0], output_types, test_feat1)
  File "/PATH/MTDSITE/MTDsite/code/PROST/script/spider3_pred.py", line 203, in run_batch1
    RNN1_fw, RNN1_state_fw = run_RNN(x, RNN1_FW_matrix, RNN1_FW_bias, batch_seq_len_mask)
  File "/PATH/MTDSITE/MTDsite/code/PROST/script/spider3_pred.py", line 43, in run_RNN
    inprod = np.dot(temp_x, matrix_in) 
  File "<__array_function__ internals>", line 180, in dot
ValueError: shapes (1,1081) and (313,1024) not aligned: 1081 (dim 1) != 313 (dim 0)

"""

Do you have an idea of how could i fix that ?
Thank you !

**Comment by ShahidIqb** [comment]
Hi, 
The apparent reason for this is the NumPy version you use in your virtual environment. Please check and re-install the correct version of NumPy. You can also check the Spakrs lab on how to run spider3 (https://sparks-lab.org/server/spider3/)

**Comment by Ravy-LFL** [comment]
Okay, do you know which version should i use ? i would like to run it on several proteins that's why i need it in standalone

**Comment by Ravy-LFL** [comment]
I cannot reach the webserver ? Is this normal ?

**Comment by ShahidIqb** [comment]
Can you please look into the RequirementsPy2 for the Python2 virtual environment? All the requirements are listed.

Regarding the webserver, I noticed it's running locally but not accessible on the public network. I'm sorry for the downtime; the server is down because of some issues in the system. In the meantime, you can try this link http://202.119.84.36:3079/prost/

**Comment by Ravy-LFL** [comment]
I need python3 to use it with MTDSITE, but when i try RequirementsPy3 it cannot find dssp ? Which version should i use ?

**Comment by Ravy-LFL** [comment]
I also have this error with the computations of the matrices : """
Traceback (most recent call last):
  File "/PATH/MTDSITE/MTDsite/code/PROST/script/spider3_pred.py", line 284, in <module>
    run_all(list_dict_nn, [bn], opts)
  File "/PATH/MTDSITE/MTDsite/code/PROST/script/spider3_pred.py", line 132, in run_all
    out1 = run_batch1(check_dat[0], output_types, test_feat1)
  File "/PATH/MTDSITE/MTDsite/code/PROST/script/spider3_pred.py", line 207, in run_batch1
    RNN1_fw, RNN1_state_fw = run_RNN(x, RNN1_FW_matrix, RNN1_FW_bias, batch_seq_len_mask)
  File "/PATH/MTDSITE/MTDsite/code/PROST/script/spider3_pred.py", line 24, in run_RNN
    output = np.zeros([inputs.shape[0], inputs.shape[1], matrix_in.shape[1]/4]) #The real lines
TypeError: 'float' object cannot be interpreted as an integer
"""

**Comment by ShahidIqb** [comment]
For the DSSP program, you can look at the following code. Can you run this code on one of your PDB files and check whether it works? Here you'll need to provide the PDB file, chain, and residue position.

Note: BioPython is required for this.

from Bio.PDB import PDBParser
from Bio.PDB.DSSP import DSSP
file_in = ""
chain = ""
position=
    
"""This code uses DSSP program to calculate RSA, phi, and psi"""
p = PDBParser(QUIET=True)
structure = p.get_structure('xxx', file_in)
model = structure[0]
dssp = DSSP(model, file_in, dssp='mkdssp')
print(dssp[(chain, (' ', position, ' '))][3:6])
